apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    name: roboshop
    environement: dev
    component: mysql
    tier: backend
spec:
  containers:
  - name: nginx
    image: nginx