apiVersion: v1
kind: Pod
metadata:
  name: env-var-demo
  labels:
    purpose: demonstrate-env-vars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: KUBERNATES
    - name: Lakshmi
      value: STUDENT