apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
spec:
  selector:
    purpose: service-lb-demo
    project: roboshop
    env: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # nginx port
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx

